name: shadesmaster
description: "Helping dentists to pick their tooth shades"
publish_to: 'none'

version: 2.0.4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image: ^4.2.0
  hugeicons: ^1.1.5
  shared_preferences: ^2.5.4
  uuid: ^4.5.3
  intl: ^0.20.2
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4


dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  archive: ^3.6.1
  yaml: ^3.1.2
  path: ^1.9.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png